### ISSUE TITLE
detectLableResults is unbound

### ISSUE THREAD

**Issue by vazkarvishal** [aws-samples/aws-dev-hour-backend#12]
![image](https://user-images.githubusercontent.com/13076513/106434721-d43c5700-6469-11eb-9fab-0591ec683ca1.png)

Need to declare an empty dictionary in the function to avoid linting errors.

**Comment by newtondigital** [comment]
Thank you for calling this out! I have remediated; please go ahead and pull changes.

**Comment by newtondigital** [comment]
Unbound dict remediated.
