### ISSUE TITLE
No module named 'PIL'

### ISSUE THREAD

**Issue by SanazME** [aws-samples/aws-dev-hour-backend#17]
Following the lecture, when I uploaded an image to s3 bucket using the CLI, I check the cloudwatch for the logs and noticed that there was a runtime error related to PIL module not being found:

[ERROR] Runtime.ImportModuleError: Unable to import module 'index': No module named 'PIL'

and scanning the dynamodb did not return any item.

**Comment by cindyledev** [comment]
As mentioned in the stream, you had to get the Pillow library for the reklayer to work. The instructions are also in the [README](https://github.com/aws-samples/aws-dev-hour-backend#aws-lambda---creating-assets-for-your-aws-lambda-layer) doc.

**Comment by piedpiper-ff4084** [comment]
@SanazME you can use this zip file. 
[pillow.zip](https://github.com/aws-samples/aws-dev-hour-backend/files/5948826/pillow.zip)

**Comment by IAM-DBro** [comment]
Hey @piedpiper-ff4084 I included the extracted zip of your pillow attachment, thanks for including that here.

After a fresh "cdk snyth"and "cdk deploy" I still get "Unable to import module 'index': No module named 'PIL'.

Is there still something I'm perhaps missing?
![image](https://user-images.githubusercontent.com/22583402/107875659-1f6a5700-6eb9-11eb-8571-17b8f3d092cd.png)

**Comment by piedpiper-ff4084** [comment]
Hi @IAM-DBro,

hmm... I have the same reklayer file structure.
Can you try doing a clean up and then redeploying the app?
`aws s3 rm --recursive s3://{imageBucket}
cdk destroy`


`npm install
cdk deploy`

**Comment by IAM-DBro** [comment]
Hey @piedpiper-ff4084 thanks for getting back to me so quickly.

The output is quite large from `cdk synth` is there a suitable way to show you its results?
I'm running through cleanup and re-deploy now but have done so a few times.

Do I need the re-sized bucket component in place or the service lambda in place yet? I see them in the main codebase but I know week 1 hasn't gone over it yet.

**Comment by piedpiper-ff4084** [comment]
Hey @IAM-DBro,
The re-sized bucket component should be created as part of the stack during the deployment.
Do you mind creating a feature branch and pushing your changes, so that I can try deploying your changes?

**Comment by IAM-DBro** [comment]
I've my own github which has all latest changes if that's easier.
https://github.com/DarrenBro/modernApp-AWS-CDK

I don't see the re-size bucket after cdk deploy.

One 1 bucket that takes the image and 1 dynamo db.

**Comment by piedpiper-ff4084** [comment]
Hey @IAM-DBro,

I checked out your code and you are missing the creation of the lambda layer. This is why you are unable to import the PIL library when your rekognitionlambda is executed.
See here:
https://github.com/aws-samples/aws-dev-hour-backend/blob/main/lib/awsdevhour-stack.ts#L46

Also you need to add the lambda layer to your rekognitionlambda.
See here:
https://github.com/aws-samples/aws-dev-hour-backend/blob/main/lib/awsdevhour-stack.ts#L62

After you make these changes to your CdkMainStack.ts file then try redeploying again.

**Comment by IAM-DBro** [comment]
Worked a treat thanks so much!
![image](https://user-images.githubusercontent.com/22583402/107890710-3a1cea00-6f12-11eb-82dc-67b75e29055b.png)

I've honoured you in my comments and soon commit message.

**Comment by piedpiper-ff4084** [comment]
Thanks! Glad I could help @IAM-DBro.
